/**
 * ManageSpace Note API
 * ManageSpace Note API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { EntityRequest } from './entityRequest';

export class CreateNoteRequest {
    /**
    * Note title.
    */
    'title': string;
    /**
    * Note text.
    */
    'text': string;
    /**
    * Optional array of tag ids.
    */
    'tags': Array<string> | null;
    /**
    * A list of entity objects containing id and type.
    */
    'entities': Array<EntityRequest> | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "string"
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<string>"
        },
        {
            "name": "entities",
            "baseName": "entities",
            "type": "Array<EntityRequest>"
        }    ];

    static getAttributeTypeMap() {
        return CreateNoteRequest.attributeTypeMap;
    }
}

