/**
 * ManageSpace Note API
 * ManageSpace Note API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class EntityRequest {
    /**
    * Entity code name.
    */
    'entityTypeCodeName': string;
    /**
    * Identified of the entity.
    */
    'entityId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "entityTypeCodeName",
            "baseName": "entityTypeCodeName",
            "type": "string"
        },
        {
            "name": "entityId",
            "baseName": "entityId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return EntityRequest.attributeTypeMap;
    }
}

