/**
 * ManageSpace Note API
 * ManageSpace Note API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { NoteEntityResponse } from './noteEntityResponse';
import { TagResponse } from './tagResponse';

export class NoteResponse {
    /**
    * Note Id
    */
    'noteId': string;
    /**
    * Note title
    */
    'title': string;
    /**
    * Note text body
    */
    'text': string;
    /**
    * Org Id
    */
    'orgId': string;
    /**
    * Site Id
    */
    'siteId': string;
    /**
    * Created by
    */
    'createdBy': string;
    /**
    * Created at.
    */
    'createdAt': string;
    /**
    * Full name of the creator of the note.
    */
    'createdByFullName': string;
    /**
    * Org tags associated with this note.
    */
    'tags': Array<TagResponse>;
    /**
    * Entities associated with this note.
    */
    'entities': Array<NoteEntityResponse>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "noteId",
            "baseName": "noteId",
            "type": "string"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "string"
        },
        {
            "name": "orgId",
            "baseName": "orgId",
            "type": "string"
        },
        {
            "name": "siteId",
            "baseName": "siteId",
            "type": "string"
        },
        {
            "name": "createdBy",
            "baseName": "createdBy",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "string"
        },
        {
            "name": "createdByFullName",
            "baseName": "createdByFullName",
            "type": "string"
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<TagResponse>"
        },
        {
            "name": "entities",
            "baseName": "entities",
            "type": "Array<NoteEntityResponse>"
        }    ];

    static getAttributeTypeMap() {
        return NoteResponse.attributeTypeMap;
    }
}

