/**
 * ManageSpace Note API
 * ManageSpace Note API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class NoteEntityResponse {
    /**
    * Note entity id.
    */
    'noteEntityId': string;
    /**
    * Entity id.
    */
    'entityId': string;
    /**
    * Entity type id.
    */
    'entityTypeId': NoteEntityResponse.EntityTypeIdEnum;
    /**
    * Entity code name.
    */
    'entityTypeCodeName': NoteEntityResponse.EntityTypeCodeNameEnum;
    /**
    * Entity display name.
    */
    'entityTypeDisplayName': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "noteEntityId",
            "baseName": "noteEntityId",
            "type": "string"
        },
        {
            "name": "entityId",
            "baseName": "entityId",
            "type": "string"
        },
        {
            "name": "entityTypeId",
            "baseName": "entityTypeId",
            "type": "NoteEntityResponse.EntityTypeIdEnum"
        },
        {
            "name": "entityTypeCodeName",
            "baseName": "entityTypeCodeName",
            "type": "NoteEntityResponse.EntityTypeCodeNameEnum"
        },
        {
            "name": "entityTypeDisplayName",
            "baseName": "entityTypeDisplayName",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return NoteEntityResponse.attributeTypeMap;
    }
}

export namespace NoteEntityResponse {
    export enum EntityTypeIdEnum {
        NUMBER_1 = <any> 1,
        NUMBER_2 = <any> 2,
        NUMBER_3 = <any> 3,
        NUMBER_4 = <any> 4
    }
    export enum EntityTypeCodeNameEnum {
        Contact = <any> 'contact',
        Company = <any> 'company',
        Unit = <any> 'unit',
        Invoice = <any> 'invoice'
    }
}
