/**
 * ManageSpace Note API
 * ManageSpace Note API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class TagResponse {
    /**
    * Tag Id
    */
    'tagId': string;
    /**
    * Tag text
    */
    'text': string;
    /**
    * Organization Id
    */
    'orgId': string;
    /**
    * Site Id
    */
    'siteId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "tagId",
            "baseName": "tagId",
            "type": "string"
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "string"
        },
        {
            "name": "orgId",
            "baseName": "orgId",
            "type": "string"
        },
        {
            "name": "siteId",
            "baseName": "siteId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return TagResponse.attributeTypeMap;
    }
}

